export const courses = [
  {
    id: 1,
    courseCode: "ELEC201",
    title: "Digital Electronics",
    description:
      "An introduction to digital logic, Boolean algebra, combinational and sequential circuits, and microprocessors. Emphasis on design and implementation.",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 3,
    instructor: "Dr. Emily Carter",
    availableSeats: 25,
  },
  {
    id: 2,
    courseCode: "MATH210",
    title: "Calculus II",
    description:
      "A continuation of Calculus I, covering integration techniques, applications of integration, sequences and series, and an introduction to differential equations.",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 4,
    instructor: "Professor David Lee",
    availableSeats: 30,
  },
  {
    id: 3,
    courseCode: "CS102",
    title: "Introduction to Programming",
    description:
      "A beginner-friendly introduction to programming concepts, using Python. Covers variables, data types, control flow, functions, and basic data structures.",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 3,
    instructor: "Ms. Sarah Johnson",
    availableSeats: 40,
  },
  {
    id: 4,
    courseCode: "ENG102",
    title: "Composition II",
    description:
      "Building upon Composition I, this course focuses on advanced writing skills, research methods, and critical analysis. Emphasis on argumentative and persuasive writing.",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 3,
    instructor: "Mr. Michael Brown",
    availableSeats: 20,
  },
  {
    id: 5,
    courseCode: "HIST102",
    title: "World History II",
    description:
      "A continuation of World History I, covering major historical events and developments from the Renaissance to the present day.",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 3,
    instructor: "Dr. Maria Garcia",
    availableSeats: 35,
  },
  {
    id: 6,
    courseCode: "PHYS202",
    title: "Physics II",
    description:
      "Building upon Physics I, this course covers electricity, magnetism, optics, and modern physics concepts.",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 4,
    instructor: "Professor Robert Wilson",
    availableSeats: 28,
  },
  {
    id: 7,
    courseCode: "CHEM102",
    title: "Chemistry II",
    description:
      "Building upon Chemistry I, this course covers chemical equilibrium, thermodynamics, kinetics, and an introduction to organic chemistry.",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 4,
    instructor: "Dr. Jennifer Davis",
    availableSeats: 32,
  },
  {
    id: 8,
    courseCode: "BIO102",
    title: "Biology II",
    description:
      "Building upon Biology I, this course covers genetics, evolution, ecology, and an introduction to animal physiology.",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 4,
    instructor: "Professor Thomas Anderson",
    availableSeats: 26,
  },
  {
    id: 9,
    courseCode: "PSY102",
    title: "Introduction to Psychology",
    description:
      "An introductory view to what psychology is, including key learnings and what impacts them today",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 3,
    instructor: "Dr. Stacy William",
    availableSeats: 24,
  },
  {
    id: 10,
    courseCode: "ECON101",
    title: "Microeconomics",
    description:
      "Focusing on the individual, Microeconomics focuses on the individuals",
    semester: "Second Semester",
    academicYear: "2024/2025",
    credits: 3,
    instructor: "Dr. Stacy William",
    availableSeats: 24,
  },
];